# nixpacks.toml
[phases.setup]
nixPkgs = ["nginx"]  # Use Nginx to serve the static site

[phases.build]
cmds = []  # No build commands needed since /build is pre-generated

[phases.start]
cmd = "nginx -g 'daemon off;'"  # Start Nginx

[staticAssets]
publicDir = "build"  # Serve static files from the /build directory
